In [1]:
import numpy as np
import pandas as pd

In [2]:
#extract goal attribute relation
file_name='.\\Network_Traffic_Packet_Record_v1.csv'
Network_Traffic_record=pd.read_csv(file_name, low_memory=False) 
Network_Traffic_record

,Solution,Solution Name,Atrribute
0,Sn6,Record of network traffic packet's UDP attribu...,udp.stream
1,Sn6,Record of network traffic packet's UDP attribu...,udp.time_delta
2,Sn11,Record of network traffic packet's HTTP attrib...,http.request.method
3,Sn11,Record of network traffic packet's HTTP attrib...,http.request.version
4,Sn11,Record of network traffic packet's HTTP attrib...,http.referer
5,Sn11,Record of network traffic packet's HTTP attrib...,http.response
6,Sn11,Record of network traffic packet's HTTP attrib...,http.content_length
7,Sn11,Record of network traffic packet's HTTP attrib...,http.tls_port
8,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack
9,Sn14,Record of network traffic packet's TCP attribu...,tcp.flags
10,Sn14,Record of network traffic packet's TCP attribu...,tcp.len
11,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack_raw
12,Sn14,Record of network traffic packet's TCP attribu...,tcp.checksum
13,Sn14,Record of network traffic packet's TCP attribu...,tcp.seq
14,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.syn
15,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.fin
16,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.synack
17,Sn14,Record of network traffic packet's TCP attribu...,tcp.flags.ack
18,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.rst

In [3]:
#extract all_possible path
file_name='.\All_possible_path.txt'
All_possible_path=pd.read_csv(file_name, low_memory=False) 
All_possible_path
#All_possible_path.info()

                                                Paths
0   SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-24|S19|G-...
1   SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-24|S19|G-...
2   SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-24|S19|G-...
3        SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn10
4        SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
5        SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
6        SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn13
7        SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
8        SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn13
9        SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
10        SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn6
11       SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn10
12       SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-20|Sn10
13       SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
14       SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
15       SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-18|Sn12
16       SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
17        SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn6
18       SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn10
19        SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn6
20        SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn9
21        SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn6
22        SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn8
23        SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|Sn6
24  SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|S23|G-...
25                        SI-4 Main|S9|G-4|S8|G-9|Sn2
26                        SI-4 Main|S9|G-4|S7|G-8|Sn5
27                 SI-4 Main|S9|G-4|S3|G-5|S5|G-7|Sn5
28                 SI-4 Main|S9|G-4|S3|G-5|S4|G-6|Sn5
29                        SI-4 Main|S9|G-4|S3|G-5|Sn2
30  SI-4 Main|SC-5(3) Main|S2|SC-5(3) Req|G-4|S8|G...
31  SI-4 Main|SC-5(3) Main|S2|SC-5(3) Req|G-4|S7|G...
32  SI-4 Main|SC-5(3) Main|S2|SC-5(3) Req|G-4|S3|G...
33  SI-4 Main|SC-5(3) Main|S2|SC-5(3) Req|G-4|S3|G...
34  SI-4 Main|SC-5(3) Main|S2|SC-5(3) Req|G-4|S3|G...
35  SI-4 Main|SC-5(3) Main|S2|SC-5(3) Req|G-5|S5|G...
36  SI-4 Main|SC-5(3) Main|S2|SC-5(3) Req|G-5|S4|G...
37      SI-4 Main|SC-5(3) Main|S2|SC-5(3) Req|G-5|Sn2
38      SI-4 Main|SC-5(3) Main|S2|SC-5(3) Req|G-3|Sn4
39      SI-4 Main|SC-5(3) Main|S2|SC-5(3) Req|G-2|Sn3
40  SI-4 Main|SC-5(3) Main|SC-5 Main|S1|SC-5 Req|G...
41  SI-4 Main|SC-5(3) Main|SC-5 Main|S1|SC-5 Req|G...
42         SC-5(3) Main|S2|SC-5(3) Req|G-4|S8|G-9|Sn2
43         SC-5(3) Main|S2|SC-5(3) Req|G-4|S7|G-8|Sn5
44  SC-5(3) Main|S2|SC-5(3) Req|G-4|S3|G-5|S5|G-7|Sn5
45  SC-5(3) Main|S2|SC-5(3) Req|G-4|S3|G-5|S4|G-6|Sn5
46         SC-5(3) Main|S2|SC-5(3) Req|G-4|S3|G-5|Sn2
47         SC-5(3) Main|S2|SC-5(3) Req|G-5|S5|G-7|Sn5
48         SC-5(3) Main|S2|SC-5(3) Req|G-5|S4|G-6|Sn5
49                SC-5(3) Main|S2|SC-5(3) Req|G-5|Sn2
50                SC-5(3) Main|S2|SC-5(3) Req|G-3|Sn4
51                SC-5(3) Main|S2|SC-5(3) Req|G-2|Sn3
52         SC-5(3) Main|SC-5 Main|S1|SC-5 Req|G-1|Sn2
53         SC-5(3) Main|SC-5 Main|S1|SC-5 Req|G-1|Sn1

In [4]:
# import pandas as pd

# def find_primary_immediate_goal_for_solution(df_input):
#     """
#     Finds a single primary immediate goal for each solution based on matching paths.
#     If multiple immediate goals exist for a solution in a given row,
#     the alphabetically first one is chosen.

#     Args:
#         df_input (pd.DataFrame): DataFrame containing 'Solution' and 'Matching Paths' columns.
#                                  'Matching Paths' should contain semicolon-separated path strings
#                                  where each path is a pipe-separated sequence of nodes.

#     Returns:
#         pd.DataFrame: The input DataFrame with a new column 'Primary Immediate Goal'
#                       containing the single chosen immediate goal (or pd.NA if none found).
#     """
#     # Work on a copy to avoid SettingWithCopyWarning if df_input might be a slice
#     df = df_input.copy()
#     new_col_name = "Primary Immediate Goal"
#     df[new_col_name] = pd.NA  # Initialize the new column with NA (Not Available)

#     for idx, row in df.iterrows():
#         # Ensure solution_node is treated as a string for consistent matching
#         solution_node = str(row["Solution"])
#         paths_string = row["Matching Paths"]

#         immediate_goals_for_row = set() # Use a set to store unique goals found for this row

#         if pd.isna(paths_string) or not paths_string.strip():
#             # No paths, so Primary Immediate Goal remains pd.NA
#             continue

#         individual_paths = paths_string.split(';')

#         for path_str_raw in individual_paths:
#             path_str = path_str_raw.strip()  # Clean up whitespace
#             if not path_str:  # Skip if path string is empty after stripping
#                 continue

#             elements = path_str.split('|')

#             # Check if the path is long enough and the last element is the solution_node
#             if len(elements) >= 2 and elements[-1] == solution_node:
#                 potential_immediate_goal = elements[-2]
#                 # Check if this preceding element is a goal (starts with 'G')
#                 if potential_immediate_goal.startswith('G'):
#                     immediate_goals_for_row.add(potential_immediate_goal)

#         if immediate_goals_for_row:
#             # If one or more immediate goals were found, sort them and pick the first one
#             chosen_goal = sorted(list(immediate_goals_for_row))[0]
#             df.loc[idx, new_col_name] = chosen_goal
#             #print("solution_node paths_string",solution_node,paths_string)
#         # If no immediate goals were found (set is empty), it remains pd.NA

#     return df

In [5]:
# # Your existing function (ensure it correctly populates 'Matching Paths')
# def add_paths_to_goals(gsn_df_orig, paths_df):
#     gsn_df = gsn_df_orig.copy() # Work on a copy
#     gsn_df["Matching Paths"] = ""

#     for idx, gsn_row in gsn_df.iterrows():
#         matching_paths_list = [] # Changed variable name for clarity
#         current_solution_node = str(gsn_row["Solution"]) # Ensure string for comparison

#         for _, path_row in paths_df.iterrows():
#             path_str = path_row["Paths"]
#             path_elements = path_str.split('|')
#             # Check if the solution node is an element in the path
#             # For more accuracy, you might want to check if it's specifically the last element
#             # if paths are always leading directly to the solution.
#             # However, sticking to "in path_elements" to match "in path" logic broadly.
#             if current_solution_node in path_elements:
#                 matching_paths_list.append(path_str)

#         gsn_df.loc[idx, "Matching Paths"] = "; ".join(matching_paths_list)
#     return gsn_df

# # Assuming Network_Traffic_record and All_possible_path DataFrames are loaded
# # Example:
# # Network_Traffic_record = pd.read_csv('your_network_traffic_record.csv')
# # All_possible_path = pd.read_csv('your_all_paths.csv')

# gsn_df_with_paths = add_paths_to_goals(Network_Traffic_record, All_possible_path)
# gsn_df_with_paths
# # Apply the function to find the primary immediate goal
# df_with_primary_goal = find_primary_immediate_goal_for_solution(gsn_df_with_paths)

# # Display the result
# print(df_with_primary_goal[['Solution', 'Atrribute', 'Matching Paths', 'Primary Immediate Goal']])
# df_with_primary_goal

In [6]:
import pandas as pd

def create_solution_goal_pair_rows(df_input):
    """
    Transforms the DataFrame to create a distinct row for each
    (Solution, Immediate Goal) pair, with the 'Matching Paths' column
    updated to show only the specific path relevant to that pair.

    Args:
        df_input (pd.DataFrame): DataFrame containing at least 'Solution' and
                                 'Matching Paths' columns. Other columns will be
                                 duplicated in the output.

    Returns:
        pd.DataFrame: A new DataFrame where rows from df_input are exploded
                      for each unique (immediate goal, specific path) found
                      for a solution. Includes 'Immediate Goal' and updates
                      'Matching Paths' to the specific path. Rows from the
                      input that do not yield any (Solution, Immediate Goal)
                      pairs are excluded.
    """
    if df_input.empty:
        # If input is empty, return an empty DataFrame with expected columns
        # 'Immediate Goal' is new, 'Matching Paths' content would be specific.
        output_cols = df_input.columns.tolist()
        if "Immediate Goal" not in output_cols:
            output_cols.append("Immediate Goal")
        return pd.DataFrame(columns=output_cols)

    df = df_input.copy()
    # This temporary column will store a list of (immediate_goal, specific_path) tuples
    temp_goal_path_pairs_col = "_internal_goal_path_pairs"

    # Helper function to apply to each row
    def get_all_immediate_goal_path_pairs_for_row(row_series):
        solution_node = str(row_series["Solution"])
        # This 'Matching Paths' is the semicolon-separated string of ALL paths for the solution
        paths_string = row_series["Matching Paths"] 
        
        goal_path_pairs = [] # To store (goal, specific_path) tuples

        if pd.isna(paths_string) or not paths_string.strip():
            return [] # Return an empty list if no paths information

        individual_paths = paths_string.split(';')
        for path_str_raw in individual_paths:
            path_str = path_str_raw.strip()
            if not path_str:
                continue
            
            elements = path_str.split('|')
            # Check if path is long enough and ends with the solution node
            if len(elements) >= 2 and elements[-1] == solution_node:
                potential_immediate_goal = elements[-2]
                # Check if the preceding element is a goal
                if potential_immediate_goal.startswith('G'):
                    # Add the (goal, specific path that led to it) tuple
                    goal_path_pairs.append((potential_immediate_goal, path_str))
        
        # Return a list of unique (goal, path) tuples for this solution row
        # If multiple distinct paths lead to the same goal, each will be a separate entry.
        # If the same path is listed multiple times leading to the same goal, it will be unique here.
        return list(set(goal_path_pairs))

    # 1. Create a temporary column with the list of (immediate_goal, specific_path) pairs
    df[temp_goal_path_pairs_col] = df.apply(get_all_immediate_goal_path_pairs_for_row, axis=1)

    # 2. Filter out rows that didn't yield any (goal, path) pairs
    df_with_pairs = df[df[temp_goal_path_pairs_col].map(len) > 0].copy()

    if df_with_pairs.empty:
        # If no rows have any valid pairs after processing,
        # return an empty DataFrame with the correct columns
        output_cols = df_input.columns.tolist()
        if "Immediate Goal" not in output_cols:
            output_cols.append("Immediate Goal")
        return pd.DataFrame(columns=output_cols)

    # 3. Explode the DataFrame based on the list of (goal, path) pairs
    df_exploded = df_with_pairs.explode(temp_goal_path_pairs_col)

    # 4. Populate 'Immediate Goal' from the first element of the pair
    #    and overwrite 'Matching Paths' with the second element (the specific path)
    #    Handle cases where a row might become all NaN after explode if a list was empty (though filtered)
    df_exploded_valid = df_exploded.dropna(subset=[temp_goal_path_pairs_col]).copy()


    df_exploded_valid["Immediate Goal"] = df_exploded_valid[temp_goal_path_pairs_col].apply(lambda x: x[0])
    # Overwrite the 'Matching Paths' column with the specific path for this goal
    df_exploded_valid["Matching Paths"] = df_exploded_valid[temp_goal_path_pairs_col].apply(lambda x: x[1])
    
    # 5. Define final columns: all original columns (with 'Matching Paths' now updated)
    #    plus the new 'Immediate Goal' column. Drop the temporary processing column.
    final_columns = df_input.columns.tolist()
    if "Immediate Goal" not in final_columns:
        final_columns.append("Immediate Goal") # Ensure 'Immediate Goal' is in the list
    
    df_output = df_exploded_valid[final_columns].copy()
    df_output = df_output.reset_index(drop=True)
#print(df_reset)
    return df_output

# Your existing function to find all paths for each solution remains unchanged
# def add_paths_to_goals(gsn_df_orig, paths_df):
#     ... (as provided) ...

# --- Step 1: Generate gsn_df_with_paths ---
# Assuming Network_Traffic_record and All_possible_path DataFrames are defined elsewhere
# gsn_df_with_paths = add_paths_to_goals(Network_Traffic_record, All_possible_path)

# --- Step 2: Create the Solution-Goal pair rows with specific paths ---
# df_solution_goal_pairs = create_solution_goal_pair_rows_revised(gsn_df_with_paths) # Use the revised function
# print("--- DataFrame with Solution-Goal Pairs and Specific Matching Paths ---")
# print(df_solution_goal_pairs)

In [7]:
# Your existing function to find all paths for each solution
# (It's good practice for this function to work on a copy if it modifies the input)
def add_paths_to_goals(gsn_df_orig, paths_df):
    gsn_df = gsn_df_orig.copy()
    gsn_df["Matching Paths"] = ""
    for idx, gsn_row in gsn_df.iterrows():
        matching_paths_list = []
        current_solution_node = str(gsn_row["Solution"])
        for _, path_row in paths_df.iterrows():
            path_str = path_row["Paths"]
            # It's more robust to check if current_solution_node is an element
            # rather than just a substring, e.g., if path_str.split('|') contains current_solution_node
            if current_solution_node in path_str.split('|'): # Assuming solution is a distinct node
                matching_paths_list.append(path_str)
                print("Solution, ",current_solution_node,path_str)
        gsn_df.loc[idx, "Matching Paths"] = "; ".join(matching_paths_list)
    return gsn_df

#
# --- Step 1: Generate gsn_df_with_paths ---
gsn_df_with_paths = add_paths_to_goals(Network_Traffic_record, All_possible_path)
# print("--- DataFrame with Matching Paths ---")
# print(gsn_df_with_paths)
# print("\n")

# --- Step 2: Create the Solution-Goal pair rows ---
df_solution_goal_pairs = create_solution_goal_pair_rows(gsn_df_with_paths)

# --- Display the result ---
print("--- DataFrame with Solution-Goal Pairs (Exploded) ---")
# if not df_solution_goal_pairs.empty:
#     # Display relevant columns, including the new 'Immediate Goal'
#     print(df_solution_goal_pairs[['Solution', 'Solution Name', 'Atrribute', 'Immediate Goal', 'Matching Paths']])
# else:
#     print("No Solution-Goal pairs found.")
df_solution_goal_pairs[['Solution',"Immediate Goal",'Matching Paths']]

Solution,  Sn6 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn6
Solution,  Sn6 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn6
Solution,  Sn6 SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn6
Solution,  Sn6 SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn6
Solution,  Sn6 SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|Sn6
Solution,  Sn6 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn6
Solution,  Sn6 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn6
Solution,  Sn6 SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn6
Solution,  Sn6 SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn6
Solution,  Sn6 SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|Sn6
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Solution,  Sn11 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Solution,  Sn14 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
--- DataFrame with Solution-Goal Pairs (Exploded) ---

   Solution Immediate Goal                                Matching Paths
0       Sn6           G-16   SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn6
1       Sn6           G-14   SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn6
2       Sn6           G-13   SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|Sn6
3       Sn6           G-16   SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn6
4       Sn6           G-15   SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn6
..      ...            ...                                           ...
72     Sn14           G-16  SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
73     Sn14           G-22  SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
74     Sn14           G-16  SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
75     Sn14           G-21  SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
76     Sn14           G-23  SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14

[77 rows x 3 columns]

In [8]:
import pandas as pd

def extract_intermediate_strategies_goals(df_input):
    """
    Extracts intermediate strategies, a set of unique intermediate goals,
    and ordered series of intermediate goals from paths in a DataFrame.
    'SI-' prefixed nodes (not the target goal) are considered intermediate goals.

    Args:
        df_input (pd.DataFrame): DataFrame with an 'Immediate Goal' column (which defines
                                 the target goal for path segment analysis) and a
                                 'Matching Paths' column. 'Matching Paths' should
                                 contain semicolon-separated path strings, where each
                                 path is a pipe-separated sequence of nodes.

    Returns:
        pd.DataFrame: The input DataFrame with three new columns:
                      'Intermediate Strategies' (comma-separated string of unique strategies).
                      'Intermediate Goals' (comma-separated string of unique intermediate goals,
                                           including G- and SI- prefixed nodes).
                      'Ordered Intermediate Goal Series' (semicolon-separated strings;
                                                       each string is a pipe-separated,
                                                       ordered list of intermediate goals
                                                       from a qualifying path segment).
    """
    df = df_input.copy()

    df["Intermediate Strategies"] = ""
    df["Intermediate Goals"] = ""
    df["Ordered Intermediate Goal Series"] = "" # New column

    start_marker_node = "SI-4 Req"

    for idx, row in df.iterrows():
        current_target_goal = str(row["Immediate Goal"]) # Ensure string
        paths_string = row["Matching Paths"]
        print("current_target_goal",current_target_goal, paths_string)
        row_intermediate_strategies = set()
        row_unique_intermediate_goals = set()
        row_ordered_goal_series_strings = set()

        if pd.isna(paths_string) or not paths_string.strip():
            continue

        individual_paths = paths_string.split(';')

        for path_str_raw in individual_paths:
            path_str = path_str_raw.strip()
            if not path_str:
                continue

            elements = path_str.split('|')

            try:
                start_node_idx = -1
            except ValueError:
                continue 

            try:
                offset = start_node_idx + 1
                if offset >= len(elements):
                    continue
                relative_end_node_idx = elements[offset:].index(current_target_goal)
                end_node_idx = relative_end_node_idx + offset
            except ValueError:
                continue 
            
            if start_node_idx >= end_node_idx -1: 
                continue 
            
            intermediate_elements = elements[start_node_idx + 1 : end_node_idx]
            
            current_path_ordered_goals = [] 

            for el in intermediate_elements:
                # 1. Populate Intermediate Strategies set
                if el.startswith('S') and not el.startswith('Sn') and not el.startswith('SI-'):
                    row_intermediate_strategies.add(el)
                
                # 2. Check if 'el' is an intermediate goal node
                is_intermediate_goal_node = False
                # An element is an intermediate goal if it starts with 'G' or 'SI-'
                # AND it is not the current_target_goal for the segment.
                if el.startswith('G')  and el != current_target_goal:
                    is_intermediate_goal_node = True
                elif el.startswith('SI-') and el != current_target_goal:
                    is_intermediate_goal_node = True
                if is_intermediate_goal_node:
                    row_unique_intermediate_goals.add(el)
                    current_path_ordered_goals.append(el)

            if current_path_ordered_goals:
                row_ordered_goal_series_strings.add("|".join(current_path_ordered_goals))
        print("current_target_goal row_intermediate_strategies",current_target_goal,row_intermediate_strategies,row_unique_intermediate_goals,row_ordered_goal_series_strings)
        df.loc[idx, "Intermediate Strategies"] = ", ".join(sorted(list(row_intermediate_strategies)))
        df.loc[idx, "Intermediate Goals"] = ", ".join(sorted(list(row_unique_intermediate_goals)))
        df.loc[idx, "Ordered Intermediate Goal Series"] = "; ".join(sorted(list(row_ordered_goal_series_strings)))
        print(df.loc[idx, ['Matching Paths', 'Immediate Goal', 'Intermediate Goals']])
    return df

In [9]:
gsn_df_with_paths=extract_intermediate_strategies_goals(df_solution_goal_pairs)
gsn_df_with_paths

current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn6
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn6
Immediate Goal                                               G-16
Intermediate Goals                      G-12, SI-4 Main, SI-4 Req
Name: 0, dtype: object
current_target_goal G-14 SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn6
current_target_goal row_intermediate_strategies G-14 {'S12', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn6
Immediate Goal                                               G-14
Intermediate Goals                      G-10, SI-4 Main, SI-4 Req
Name: 1, dtype: object
current_target_goal G-13 SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|Sn6
current_target_goal row_intermediate_strategies G-13 {'S11', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|Sn6
Immediate Goal                                               G-13
Intermediate Goals                      G-10, SI-4 Main, SI-4 Req
Name: 2, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn6
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn6
Immediate Goal                                               G-16
Intermediate Goals                      G-10, SI-4 Main, SI-4 Req
Name: 3, dtype: object
current_target_goal G-15 SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn6
current_target_goal row_intermediate_strategies G-15 {'S13', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn6
Immediate Goal                                               G-15
Intermediate Goals                      G-10, SI-4 Main, SI-4 Req
Name: 4, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn6
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn6
Immediate Goal                                               G-16
Intermediate Goals                      G-12, SI-4 Main, SI-4 Req
Name: 5, dtype: object
current_target_goal G-14 SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn6
current_target_goal row_intermediate_strategies G-14 {'S12', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn6
Immediate Goal                                               G-14
Intermediate Goals                      G-10, SI-4 Main, SI-4 Req
Name: 6, dtype: object
current_target_goal G-13 SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|Sn6
current_target_goal row_intermediate_strategies G-13 {'S11', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|Sn6
Immediate Goal                                               G-13
Intermediate Goals                      G-10, SI-4 Main, SI-4 Req
Name: 7, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn6
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn6
Immediate Goal                                               G-16
Intermediate Goals                      G-10, SI-4 Main, SI-4 Req
Name: 8, dtype: object
current_target_goal G-15 SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn6
current_target_goal row_intermediate_strategies G-15 {'S13', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn6
Immediate Goal                                               G-15
Intermediate Goals                      G-10, SI-4 Main, SI-4 Req
Name: 9, dtype: object
current_target_goal G-19 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
current_target_goal row_intermediate_strategies G-19 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Immediate Goal                                                G-19
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 10, dtype: object
current_target_goal G-17 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
current_target_goal row_intermediate_strategies G-17 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Immediate Goal                                                G-17
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 11, dtype: object
current_target_goal G-19 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
current_target_goal row_intermediate_strategies G-19 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Immediate Goal                                                G-19
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 12, dtype: object
current_target_goal G-17 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
current_target_goal row_intermediate_strategies G-17 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Immediate Goal                                                G-17
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 13, dtype: object
current_target_goal G-19 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
current_target_goal row_intermediate_strategies G-19 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Immediate Goal                                                G-19
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 14, dtype: object
current_target_goal G-17 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
current_target_goal row_intermediate_strategies G-17 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Immediate Goal                                                G-17
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 15, dtype: object
current_target_goal G-19 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
current_target_goal row_intermediate_strategies G-19 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Immediate Goal                                                G-19
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 16, dtype: object
current_target_goal G-17 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
current_target_goal row_intermediate_strategies G-17 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Immediate Goal                                                G-17
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 17, dtype: object
current_target_goal G-19 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
current_target_goal row_intermediate_strategies G-19 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Immediate Goal                                                G-19
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 18, dtype: object
current_target_goal G-17 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
current_target_goal row_intermediate_strategies G-17 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Immediate Goal                                                G-17
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 19, dtype: object
current_target_goal G-19 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
current_target_goal row_intermediate_strategies G-19 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-19|Sn11
Immediate Goal                                                G-19
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 20, dtype: object
current_target_goal G-17 SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
current_target_goal row_intermediate_strategies G-17 {'S15', 'S10', 'S9'} {'G-11', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-11'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-11|S15|G-17|Sn11
Immediate Goal                                                G-17
Intermediate Goals                       G-11, SI-4 Main, SI-4 Req
Name: 21, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Immediate Goal                                                G-16
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 22, dtype: object
current_target_goal G-22 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
current_target_goal row_intermediate_strategies G-22 {'S17', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Immediate Goal                                                G-22
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 23, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Immediate Goal                                                G-16
Intermediate Goals                       G-10, SI-4 Main, SI-4 Req
Name: 24, dtype: object
current_target_goal G-21 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
current_target_goal row_intermediate_strategies G-21 {'S16', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Immediate Goal                                                G-21
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 25, dtype: object
current_target_goal G-23 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
current_target_goal row_intermediate_strategies G-23 {'S18', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Immediate Goal                                                G-23
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 26, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Immediate Goal                                                G-16
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 27, dtype: object
current_target_goal G-22 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
current_target_goal row_intermediate_strategies G-22 {'S17', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Immediate Goal                                                G-22
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 28, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Immediate Goal                                                G-16
Intermediate Goals                       G-10, SI-4 Main, SI-4 Req
Name: 29, dtype: object
current_target_goal G-21 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
current_target_goal row_intermediate_strategies G-21 {'S16', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Immediate Goal                                                G-21
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 30, dtype: object
current_target_goal G-23 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
current_target_goal row_intermediate_strategies G-23 {'S18', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Immediate Goal                                                G-23
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 31, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Immediate Goal                                                G-16
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 32, dtype: object
current_target_goal G-22 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
current_target_goal row_intermediate_strategies G-22 {'S17', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Immediate Goal                                                G-22
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 33, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Immediate Goal                                                G-16
Intermediate Goals                       G-10, SI-4 Main, SI-4 Req
Name: 34, dtype: object
current_target_goal G-21 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
current_target_goal row_intermediate_strategies G-21 {'S16', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Immediate Goal                                                G-21
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 35, dtype: object
current_target_goal G-23 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
current_target_goal row_intermediate_strategies G-23 {'S18', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Immediate Goal                                                G-23
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 36, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Immediate Goal                                                G-16
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 37, dtype: object
current_target_goal G-22 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
current_target_goal row_intermediate_strategies G-22 {'S17', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Immediate Goal                                                G-22
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 38, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Immediate Goal                                                G-16
Intermediate Goals                       G-10, SI-4 Main, SI-4 Req
Name: 39, dtype: object
current_target_goal G-21 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
current_target_goal row_intermediate_strategies G-21 {'S16', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Immediate Goal                                                G-21
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 40, dtype: object
current_target_goal G-23 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
current_target_goal row_intermediate_strategies G-23 {'S18', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
Immediate Goal                                                G-23
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 41, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14
Immediate Goal                                                G-16
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 42, dtype: object
current_target_goal G-22 SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
current_target_goal row_intermediate_strategies G-22 {'S17', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14
Immediate Goal                                                G-22
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 43, dtype: object
current_target_goal G-16 SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
current_target_goal row_intermediate_strategies G-16 {'S14', 'S10', 'S9'} {'SI-4 Req', 'G-10', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-10'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14
Immediate Goal                                                G-16
Intermediate Goals                       G-10, SI-4 Main, SI-4 Req
Name: 44, dtype: object
current_target_goal G-21 SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
current_target_goal row_intermediate_strategies G-21 {'S16', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}
Matching Paths        SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14
Immediate Goal                                                G-21
Intermediate Goals                       G-12, SI-4 Main, SI-4 Req
Name: 45, dtype: object
current_target_goal G-23 SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14
current_target_goal row_intermediate_strategies G-23 {'S18', 'S10', 'S9'} {'G-12', 'SI-4 Req', 'SI-4 Main'} {'SI-4 Main|SI-4 Req|G-12'}

,Solution,Solution Name,Atrribute,Matching Paths,Immediate Goal,Intermediate Strategies,Intermediate Goals,Ordered Intermediate Goal Series
0,Sn6,Record of network traffic packet's UDP attribu...,udp.stream,SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn6,G-16,"S10, S14, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
1,Sn6,Record of network traffic packet's UDP attribu...,udp.stream,SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn6,G-14,"S10, S12, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
2,Sn6,Record of network traffic packet's UDP attribu...,udp.stream,SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|Sn6,G-13,"S10, S11, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
3,Sn6,Record of network traffic packet's UDP attribu...,udp.stream,SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn6,G-16,"S10, S14, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
4,Sn6,Record of network traffic packet's UDP attribu...,udp.stream,SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn6,G-15,"S10, S13, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
...,...,...,...,...,...,...,...,...
72,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.rst,SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14,G-16,"S10, S14, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
73,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.rst,SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14,G-22,"S10, S17, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
74,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.rst,SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14,G-16,"S10, S14, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
75,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.rst,SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14,G-21,"S10, S16, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
76,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.rst,SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14,G-23,"S10, S18, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12

In [10]:
file_name='./DDoS_UDP ddos attack for 38155.csv'
exp=pd.read_csv(file_name, low_memory=False) 
exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Instance_id          10 non-null     int64
 1   Attack_type          10 non-null     object
 2   Probabilistic Value  10 non-null     float64
 3   Feature Name         10 non-null     object
 4   Expected_range       10 non-null     object
 5   Feature_Weight       10 non-null     float64
 6   Feature_Value        10 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 688.0+ bytes

In [11]:
#cols = ['Feature Name','Expected_range']
exp.sort_values(by=['Feature_Weight'],ascending=False)
# Filter out negative Feature_Weight values
exp = exp[exp['Feature_Weight'] >= 0]
exp

,Instance_id,Attack_type,Probabilistic Value,Feature Name,Expected_range,Feature_Weight,Feature_Value
1,38155,DDoS_UDP,0.999996,udp.stream,udp.stream > 0.00,0.006897,0.72642
4,38155,DDoS_UDP,0.999996,tcp.connection.fin,tcp.connection.fin <= 0.00,0.002904,0.00000
5,38155,DDoS_UDP,0.999996,tcp.ack_raw,tcp.ack_raw <= 0.15,0.002323,0.00000
6,38155,DDoS_UDP,0.999996,tcp.ack,tcp.ack <= 0.00,0.001066,0.00000

In [12]:
# Merging the tables on Feature Name (from exp) and Attribute (from S_sac)
merged_df = pd.merge(exp, gsn_df_with_paths, left_on='Feature Name', right_on='Atrribute', how='inner')

# Display the merged dataframe
print(merged_df)
#cols=[1,2,3,4,5,6,7,8]
 
S_map=merged_df#[merged_df.columns[cols]]

S_map

    Instance_id Attack_type  Probabilistic Value        Feature Name  \
0         38155    DDoS_UDP             0.999996          udp.stream
1         38155    DDoS_UDP             0.999996          udp.stream
2         38155    DDoS_UDP             0.999996          udp.stream
3         38155    DDoS_UDP             0.999996          udp.stream
4         38155    DDoS_UDP             0.999996          udp.stream
5         38155    DDoS_UDP             0.999996  tcp.connection.fin
6         38155    DDoS_UDP             0.999996  tcp.connection.fin
7         38155    DDoS_UDP             0.999996  tcp.connection.fin
8         38155    DDoS_UDP             0.999996  tcp.connection.fin
9         38155    DDoS_UDP             0.999996  tcp.connection.fin
10        38155    DDoS_UDP             0.999996         tcp.ack_raw
11        38155    DDoS_UDP             0.999996         tcp.ack_raw
12        38155    DDoS_UDP             0.999996         tcp.ack_raw
13        38155    DDoS_UDP             0.999996         tcp.ack_raw
14        38155    DDoS_UDP             0.999996         tcp.ack_raw
15        38155    DDoS_UDP             0.999996             tcp.ack
16        38155    DDoS_UDP             0.999996             tcp.ack
17        38155    DDoS_UDP             0.999996             tcp.ack
18        38155    DDoS_UDP             0.999996             tcp.ack
19        38155    DDoS_UDP             0.999996             tcp.ack

                Expected_range  Feature_Weight  Feature_Value Solution  \
0            udp.stream > 0.00        0.006897        0.72642      Sn6
1            udp.stream > 0.00        0.006897        0.72642      Sn6
2            udp.stream > 0.00        0.006897        0.72642      Sn6
3            udp.stream > 0.00        0.006897        0.72642      Sn6
4            udp.stream > 0.00        0.006897        0.72642      Sn6
5   tcp.connection.fin <= 0.00        0.002904        0.00000     Sn14
6   tcp.connection.fin <= 0.00        0.002904        0.00000     Sn14
7   tcp.connection.fin <= 0.00        0.002904        0.00000     Sn14
8   tcp.connection.fin <= 0.00        0.002904        0.00000     Sn14
9   tcp.connection.fin <= 0.00        0.002904        0.00000     Sn14
10         tcp.ack_raw <= 0.15        0.002323        0.00000     Sn14
11         tcp.ack_raw <= 0.15        0.002323        0.00000     Sn14
12         tcp.ack_raw <= 0.15        0.002323        0.00000     Sn14
13         tcp.ack_raw <= 0.15        0.002323        0.00000     Sn14
14         tcp.ack_raw <= 0.15        0.002323        0.00000     Sn14
15             tcp.ack <= 0.00        0.001066        0.00000     Sn14
16             tcp.ack <= 0.00        0.001066        0.00000     Sn14
17             tcp.ack <= 0.00        0.001066        0.00000     Sn14
18             tcp.ack <= 0.00        0.001066        0.00000     Sn14
19             tcp.ack <= 0.00        0.001066        0.00000     Sn14

                                        Solution Name           Atrribute  \
0   Record of network traffic packet's UDP attribu...          udp.stream
1   Record of network traffic packet's UDP attribu...          udp.stream
2   Record of network traffic packet's UDP attribu...          udp.stream
3   Record of network traffic packet's UDP attribu...          udp.stream
4   Record of network traffic packet's UDP attribu...          udp.stream
5   Record of network traffic packet's TCP attribu...  tcp.connection.fin
6   Record of network traffic packet's TCP attribu...  tcp.connection.fin
7   Record of network traffic packet's TCP attribu...  tcp.connection.fin
8   Record of network traffic packet's TCP attribu...  tcp.connection.fin
9   Record of network traffic packet's TCP attribu...  tcp.connection.fin
10  Record of network traffic packet's TCP attribu...         tcp.ack_raw
11  Record of network traffic packet's TCP attribu...         tcp.ack_raw
12  Record of network traffic packet's TCP attribu...         tcp.ack_raw
13  Record of network traffic packet's TCP attribu...         tcp.ack_raw
14  Record of network traffic packet's TCP attribu...         tcp.ack_raw
15  Record of network traffic packet's TCP attribu...             tcp.ack
16  Record of network traffic packet's TCP attribu...             tcp.ack
17  Record of network traffic packet's TCP attribu...             tcp.ack
18  Record of network traffic packet's TCP attribu...             tcp.ack
19  Record of network traffic packet's TCP attribu...             tcp.ack

                                  Matching Paths Immediate Goal  \
0    SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn6           G-16
1    SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn6           G-14
2    SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|Sn6           G-13
3    SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn6           G-16
4    SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn6           G-15
5   SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14           G-16
6   SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14           G-22
7   SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14           G-16
8   SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14           G-21
9   SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14           G-23
10  SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14           G-16
11  SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14           G-22
12  SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14           G-16
13  SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14           G-21
14  SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14           G-23
15  SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14           G-16
16  SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14           G-22
17  SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14           G-16
18  SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14           G-21
19  SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14           G-23

   Intermediate Strategies         Intermediate Goals  \
0             S10, S14, S9  G-12, SI-4 Main, SI-4 Req
1             S10, S12, S9  G-10, SI-4 Main, SI-4 Req
2             S10, S11, S9  G-10, SI-4 Main, SI-4 Req
3             S10, S14, S9  G-10, SI-4 Main, SI-4 Req
4             S10, S13, S9  G-10, SI-4 Main, SI-4 Req
5             S10, S14, S9  G-12, SI-4 Main, SI-4 Req
6             S10, S17, S9  G-12, SI-4 Main, SI-4 Req
7             S10, S14, S9  G-10, SI-4 Main, SI-4 Req
8             S10, S16, S9  G-12, SI-4 Main, SI-4 Req
9             S10, S18, S9  G-12, SI-4 Main, SI-4 Req
10            S10, S14, S9  G-12, SI-4 Main, SI-4 Req
11            S10, S17, S9  G-12, SI-4 Main, SI-4 Req
12            S10, S14, S9  G-10, SI-4 Main, SI-4 Req
13            S10, S16, S9  G-12, SI-4 Main, SI-4 Req
14            S10, S18, S9  G-12, SI-4 Main, SI-4 Req
15            S10, S14, S9  G-12, SI-4 Main, SI-4 Req
16            S10, S17, S9  G-12, SI-4 Main, SI-4 Req
17            S10, S14, S9  G-10, SI-4 Main, SI-4 Req
18            S10, S16, S9  G-12, SI-4 Main, SI-4 Req
19            S10, S18, S9  G-12, SI-4 Main, SI-4 Req

   Ordered Intermediate Goal Series
0           SI-4 Main|SI-4 Req|G-12
1           SI-4 Main|SI-4 Req|G-10
2           SI-4 Main|SI-4 Req|G-10
3           SI-4 Main|SI-4 Req|G-10
4           SI-4 Main|SI-4 Req|G-10
5           SI-4 Main|SI-4 Req|G-12
6           SI-4 Main|SI-4 Req|G-12
7           SI-4 Main|SI-4 Req|G-10
8           SI-4 Main|SI-4 Req|G-12
9           SI-4 Main|SI-4 Req|G-12
10          SI-4 Main|SI-4 Req|G-12
11          SI-4 Main|SI-4 Req|G-12
12          SI-4 Main|SI-4 Req|G-10
13          SI-4 Main|SI-4 Req|G-12
14          SI-4 Main|SI-4 Req|G-12
15          SI-4 Main|SI-4 Req|G-12
16          SI-4 Main|SI-4 Req|G-12
17          SI-4 Main|SI-4 Req|G-10
18          SI-4 Main|SI-4 Req|G-12
19          SI-4 Main|SI-4 Req|G-12

,Instance_id,Attack_type,Probabilistic Value,Feature Name,Expected_range,Feature_Weight,Feature_Value,Solution,Solution Name,Atrribute,Matching Paths,Immediate Goal,Intermediate Strategies,Intermediate Goals,Ordered Intermediate Goal Series
0,38155,DDoS_UDP,0.999996,udp.stream,udp.stream > 0.00,0.006897,0.72642,Sn6,Record of network traffic packet's UDP attribu...,udp.stream,SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn6,G-16,"S10, S14, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
1,38155,DDoS_UDP,0.999996,udp.stream,udp.stream > 0.00,0.006897,0.72642,Sn6,Record of network traffic packet's UDP attribu...,udp.stream,SI-4 Main|S9|SI-4 Req|S10|G-10|S12|G-14|Sn6,G-14,"S10, S12, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
2,38155,DDoS_UDP,0.999996,udp.stream,udp.stream > 0.00,0.006897,0.72642,Sn6,Record of network traffic packet's UDP attribu...,udp.stream,SI-4 Main|S9|SI-4 Req|S10|G-10|S11|G-13|Sn6,G-13,"S10, S11, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
3,38155,DDoS_UDP,0.999996,udp.stream,udp.stream > 0.00,0.006897,0.72642,Sn6,Record of network traffic packet's UDP attribu...,udp.stream,SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn6,G-16,"S10, S14, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
4,38155,DDoS_UDP,0.999996,udp.stream,udp.stream > 0.00,0.006897,0.72642,Sn6,Record of network traffic packet's UDP attribu...,udp.stream,SI-4 Main|S9|SI-4 Req|S10|G-10|S13|G-15|Sn6,G-15,"S10, S13, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
5,38155,DDoS_UDP,0.999996,tcp.connection.fin,tcp.connection.fin <= 0.00,0.002904,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.fin,SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14,G-16,"S10, S14, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
6,38155,DDoS_UDP,0.999996,tcp.connection.fin,tcp.connection.fin <= 0.00,0.002904,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.fin,SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14,G-22,"S10, S17, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
7,38155,DDoS_UDP,0.999996,tcp.connection.fin,tcp.connection.fin <= 0.00,0.002904,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.fin,SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14,G-16,"S10, S14, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
8,38155,DDoS_UDP,0.999996,tcp.connection.fin,tcp.connection.fin <= 0.00,0.002904,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.fin,SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14,G-21,"S10, S16, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
9,38155,DDoS_UDP,0.999996,tcp.connection.fin,tcp.connection.fin <= 0.00,0.002904,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.connection.fin,SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14,G-23,"S10, S18, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
10,38155,DDoS_UDP,0.999996,tcp.ack_raw,tcp.ack_raw <= 0.15,0.002323,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack_raw,SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14,G-16,"S10, S14, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
11,38155,DDoS_UDP,0.999996,tcp.ack_raw,tcp.ack_raw <= 0.15,0.002323,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack_raw,SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14,G-22,"S10, S17, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
12,38155,DDoS_UDP,0.999996,tcp.ack_raw,tcp.ack_raw <= 0.15,0.002323,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack_raw,SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14,G-16,"S10, S14, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
13,38155,DDoS_UDP,0.999996,tcp.ack_raw,tcp.ack_raw <= 0.15,0.002323,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack_raw,SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14,G-21,"S10, S16, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
14,38155,DDoS_UDP,0.999996,tcp.ack_raw,tcp.ack_raw <= 0.15,0.002323,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack_raw,SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14,G-23,"S10, S18, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
15,38155,DDoS_UDP,0.999996,tcp.ack,tcp.ack <= 0.00,0.001066,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack,SI-4 Main|S9|SI-4 Req|S10|G-12|S14|G-16|Sn14,G-16,"S10, S14, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
16,38155,DDoS_UDP,0.999996,tcp.ack,tcp.ack <= 0.00,0.001066,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack,SI-4 Main|S9|SI-4 Req|S10|G-12|S17|G-22|Sn14,G-22,"S10, S17, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
17,38155,DDoS_UDP,0.999996,tcp.ack,tcp.ack <= 0.00,0.001066,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack,SI-4 Main|S9|SI-4 Req|S10|G-10|S14|G-16|Sn14,G-16,"S10, S14, S9","G-10, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-10
18,38155,DDoS_UDP,0.999996,tcp.ack,tcp.ack <= 0.00,0.001066,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack,SI-4 Main|S9|SI-4 Req|S10|G-12|S16|G-21|Sn14,G-21,"S10, S16, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12
19,38155,DDoS_UDP,0.999996,tcp.ack,tcp.ack <= 0.00,0.001066,0.00000,Sn14,Record of network traffic packet's TCP attribu...,tcp.ack,SI-4 Main|S9|SI-4 Req|S10|G-12|S18|G-23|Sn14,G-23,"S10, S18, S9","G-12, SI-4 Main, SI-4 Req",SI-4 Main|SI-4 Req|G-12

In [13]:
#extract Degree centrality
file_name='.\weighted_pagerank.txt'
Weighted_PageRank_centrality=pd.read_csv(file_name, low_memory=False) 
Weighted_PageRank_centrality
#Degree_centrality.info()

                          Process_Name    Degree
0                    CollectSensorData  0.024590
1                   CleaningSensorData  0.032786
2                  AggregateSensorData  0.040982
3                SendSensorDataToCloud  0.049178
4                   ReceivedSensorData  0.057374
5                SendTriggerToActuator  0.086069
6            TriggerActuatorToActivate  0.094265
7               PreprocessedSensorData  0.065571
8              FeedSensorDataToMLModel  0.073768
9                       ExecuteMLModel  0.081966
10                GetMLModelPrediction  0.090165
11             DecidetoTriggerActuator  0.155743
12  ShowAnalysisResult&TriggerDecision  0.086069
13                          ReadSensor  0.008197
14                SendSensorDataToEdge  0.016393
15                         End of flow  0.036886

In [14]:
#extract Degree centrality
file_name='.\GSNIOTDDOS2_node.csv'
GSNIOTDDOS=pd.read_csv(file_name,sep='|', low_memory=False) 
GSNIOTDDOS
#Degree_centrality.info()

   Node_Type    Node_Name                                        Description
0   MainGoal    SI-4 Main               Monitor the system to detect attacks
1    ReqGoal     SC-5 Req  Configure to enabling measures on detecting at...
2    ReqGoal  SC-5(3) Req           Generate report on detecting attack type
3    ReqGoal     SI-4 Req             Monitor network traffic to detect DDoS
4   MainGoal    SC-5 Main                           denial-of-service events
..       ...          ...                                                ...
66  Strategy          S18   Argument over DecidetoTriggerActuator at Clou...
67  Strategy          S19   Argument over GetMLModelPrediction at Cloud l...
68  Strategy          S20   Argument over FeedSensorDataToMLModel at Clou...
69  Strategy          S21   Argument over PreprocessedSensorData at Cloud...
70  Strategy          S22        Argument over ExecuteMLModel at Cloud layer

[71 rows x 3 columns]

In [15]:
# import pandas as pd
# import json

# # Assume S_map DataFrame is already loaded and processed with necessary columns.

# # --- MODIFIED FUNCTION ---
# def generate_interpretation_info_from_group(group):
#     interpretation_info = []
#     for _, row in group.iterrows():
#         # Process Intermediate Strategies
#         strategies_str = row["Intermediate Strategies"]  # e.g., "S10, S14" or ""
#         strategy_list_for_json = []  # This will be a list of dictionaries

#         if strategies_str:  # True if the string is not empty
#             strategy_names = [s.strip() for s in strategies_str.split(',')]
#             strategy_names = [name for name in strategy_names if name]  # Filter out empty names

#             # Get the Process Name for the current main entry (row).
#             # This will be associated with each intermediate strategy from this row.
#             #current_process_name = row["Proc_Name"]
#             # current_process_importance = row["Degree"] # If you want to use the Degree value

#             for strat_name in strategy_names:
#                 strategy_detail = {
#                     "Strategy Name": strat_name,  # Corrected typo from "Stategy"
#                     "Process Name": "current_process_name",
#                     # Using the literal string "value" as per your snippet for Process Importance.
#                     # If you want to use the actual degree, change "value" to: current_process_importance (which would be row["Degree"])
#                     "Process Importance": "value"
#                 }
#                 strategy_list_for_json.append(strategy_detail)

#         # Process Intermediate Goals (structure remains the same as your previous full version)
#         goals_str = row["Immediate Goal"]
#         goal_list_for_json = []
#         if goals_str:  # True if the string is not empty
#             goal_names = [g.strip() for g in goals_str.split(',')]
#             goal_names = [name for name in goal_names if name]  # Filter out empty names
#             goal_list_for_json = goal_names

#         # Construct the main info dictionary
#         info = {
#             "goal": row["Immediate Goal"],
#             #"goal_Name": 'row['Goal Name]'',
#             "details": {
#                 "strategy": strategy_list_for_json,  # New structure for strategy list
#                 "Goal": goal_list_for_json , # Main process importance for the goal
#                 "attribute": row["Feature Name"],
#                 "state": row["Expected_range"],
#                 "attribute value": row["Feature_Value"],
#                 "Path": row["Matching Paths"]
#             },
#                  # Intermediate goals list (capital 'G')
#         }
#         interpretation_info.append(info)
#     return interpretation_info

# # Create the final structured data
# structured_data = []
# id=S_map.at[0,'Instance_id']

# for (attack, probability), group in grouped:
#     traffic_info = {
#         "Type": 'attack',
#         "Spec_version": "dummy",
#         "Id": str(id),
#         "Created":"N/A",
#         "modified":"N/A",
#         "Name":attack,
#         "probability":probability
        
#     }
#     interpretation_info = generate_interpretation_info_from_group(group)
    
#     structured_entry = {
#         "traffic_info": traffic_info,
#         "interpretation_info": interpretation_info
#     }
#     structured_data.append(structured_entry)

# # Convert the data to a JSON formatted string
# json_data = json.dumps(structured_data, indent=4)

# # Print the JSON data
# print(json_data)

# # Optionally, save to a file
# with open("structured_data.json", "w") as file:
#     file.write(json_data)

In [16]:
# import pandas as pd
# import json
# import io # Required if load_and_prepare_gsn_nodes handles string content directly

# # --- Helper function to load GSN node data and create a name lookup map ---
# def load_and_prepare_gsn_nodes(file_path):
#     """
#     Reads the GSN node data (pipe-delimited) and creates a lookup map
#     from Node_Name to Description.
#     Assumes 'Node_Name' and 'Description' are columns in the CSV.
#     """
#     try:
#         # Use low_memory=False if there are mixed types, though may not be needed for this file
#         df_nodes = pd.read_csv(file_path, sep='|', low_memory=False)

#         # Ensure required columns exist
#         if 'Node_Name' not in df_nodes.columns or 'Description' not in df_nodes.columns:
#             raise ValueError(f"CSV file {file_path} must contain 'Node_Name' and 'Description' columns. Found: {df_nodes.columns.tolist()}")

#         # Clean data: drop rows where Node_Name or Description is NaN, strip whitespace
#         df_cleaned = df_nodes.dropna(subset=['Node_Name', 'Description']).copy()
#         df_cleaned.loc[:, 'Node_Name'] = df_cleaned['Node_Name'].astype(str).str.strip()
#         df_cleaned.loc[:, 'Description'] = df_cleaned['Description'].astype(str).str.strip()

#         # Create map: if duplicate Node_Name exists, keep the first description
#         node_map_df = df_cleaned.drop_duplicates(subset=['Node_Name'], keep='first')
#         node_name_map = pd.Series(node_map_df['Description'].values, index=node_map_df['Node_Name']).to_dict()
        
#         return node_name_map
#     except Exception as e:
#         print(f"Error loading or processing GSN node file '{file_path}': {e}")
#         return {} # Return an empty map on error

# # --- MODIFIED generate_interpretation_info_from_group FUNCTION ---
# def generate_interpretation_info_from_group(group, node_name_map):
#     interpretation_info = []
#     for _, row in group.iterrows(): # 'row' is from S_map DataFrame

#         # Main Goal ID and Name for this interpretation_info object
#         # This 'Immediate Goal' column in S_map is assumed to be the result of a previous explode operation.
#         main_goal_id_val = row.get("Immediate Goal")
#         main_goal_id_str = "N/A"
#         main_goal_name_str = "Name not found"

#         if pd.notna(main_goal_id_val):
#             main_goal_id_str = str(main_goal_id_val).strip()
#             main_goal_name_str = node_name_map.get(main_goal_id_str, f"Name not found for ID '{main_goal_id_str}'")

#         # Process Intermediate Strategies
#         strategies_str = row.get("Intermediate Strategies", "") # Comma-separated IDs
#         strategies_list_for_json = []
#         if pd.notna(strategies_str) and strategies_str.strip():
#             strategy_ids = [s.strip() for s in strategies_str.split(',') if s.strip()]
            
#             # Use actual Process Name from the S_map row for each strategy
#             process_name_val = row.get("Proc_Name", "Process Name Not Specified")

#             for strat_id in strategy_ids:
#                 strategies_list_for_json.append({
#                     "Strategy_ID": strat_id,
#                     "Strategy_Name": node_name_map.get(strat_id, f"Name not found for ID '{strat_id}'"),
#                     "Process_Name": process_name_val,
#                     "Process_Importance": "value" # As per your previous snippet for strategies
#                 })

#         # Process Intermediate Goals (from 'Intermediate Goals' column in S_map)
#         intermediate_goals_str = row.get("Intermediate Goals", "") # Comma-separated IDs
#         intermediate_goals_list_for_json = []
#         if pd.notna(intermediate_goals_str) and intermediate_goals_str.strip():
#             intermediate_goal_ids = [g.strip() for g in intermediate_goals_str.split(',') if g.strip()]
#             for goal_id in intermediate_goal_ids:
#                 intermediate_goals_list_for_json.append({
#                     "Goal_ID": goal_id,
#                     "Goal_Name": node_name_map.get(goal_id, f"Name not found for ID '{goal_id}'")
#                 })

#         info = {
#             "goal_id": main_goal_id_str,
#             "goal_name": main_goal_name_str,
#             "details": {
#                 "strategies": strategies_list_for_json,
#                 "intermediate_goals": intermediate_goals_list_for_json,
#                 "attribute": row.get("Feature Name", "N/A"),
#                 "state": row.get("Expected_range", "N/A"),
#                 "attribute_value": row.get("Feature_Value", "N/A"),
#                 "Path": row.get("Matching Paths", "N/A")
#             }
#         }
#         interpretation_info.append(info)
#     return interpretation_info

# # --- Main script structure ---

# # 1. Load GSN node descriptions
# gsn_node_file_path = '.\\GSNIOTDDOS2_node.csv' # Make sure this path is correct
#                                             # And the CSV has 'Node_Name' and 'Description' columns.
# node_description_map = load_and_prepare_gsn_nodes(gsn_node_file_path)

# # 2. Assume S_map DataFrame is already loaded and processed.
# #    S_map should contain columns like:
# #    'Instance_id', 'Attack_type', 'Probabilistic Value',
# #    'Immediate Goal' (main goal ID for the current row, likely from explode),
# #    'Intermediate Strategies' (comma-separated IDs),
# #    'Intermediate Goals' (comma-separated IDs),
# #    'Proc_Name', 'Feature Name', 'Expected_range', 'Feature_Value', 'Matching Paths'.

# # --- Placeholder for S_map (Replace with your actual S_map DataFrame) ---
# # This S_map should be the result of your previous processing steps,
# # including the explode operation that created the 'Immediate Goal' column.



# # 3. Group S_map and generate JSON (as in your script)
# if not S_map.empty and not node_description_map == {}: # Proceed if S_map and map are loaded
#     grouped = S_map.groupby(['Attack_type', 'Probabilistic Value'])
#     structured_data = []
    
#     # Use a consistent Instance_id for each group, or make it more dynamic if needed
#     # For simplicity, taking the first from the whole S_map for the 'Id' field in traffic_info as per your script
#     s_map_instance_id = S_map['Instance_id'].iloc[0] if 'Instance_id' in S_map.columns and not S_map.empty else "Default_ID"

#     for (attack, probability), group_data in grouped:
#         traffic_info = {
#             "Type": 'attack',
#             "Spec_version": "dummy",
#             "Id": str(s_map_instance_id), # Consistent ID for the whole JSON file for now
#             "Created": "N/A",
#             "modified": "N/A",
#             "Name": attack,
#             "probability": float(probability) # Ensure probability is a JSON-compatible float
#         }
        
#         # Pass the lookup map to the generation function
#         interpretation_info_list = generate_interpretation_info_from_group(group_data, node_description_map)
        
#         structured_entry = {
#             "traffic_info": traffic_info,
#             "interpretation_info": interpretation_info_list
#         }
#         structured_data.append(structured_entry)

#     # Convert data to JSON string
#     json_data = json.dumps(structured_data, indent=4)

#     # Print JSON data
#     print(json_data)

#     # Optionally, save to a file
#     with open("structured_data_with_names.json", "w") as file:
#         file.write(json_data)
# else:
#     if S_map.empty:
#         print("S_map DataFrame is empty. Cannot generate JSON.")
#     if node_description_map == {}:
#         print("Node description map is empty (likely due to error in loading GSN nodes file). Cannot generate JSON with names.")

In [17]:
import pandas as pd
import json
import io # For file handling flexibility if needed

# --- Helper function to load GSN node data and create a name lookup map ---
def load_and_prepare_gsn_nodes(file_path):
    """
    Reads the GSN node data (pipe-delimited) and creates a lookup map
    from Node_Name to Description.
    Assumes 'Node_Name' and 'Description' are columns in the CSV.
    """
    try:
        # Use low_memory=False if there are mixed types, though may not be needed for this file
        df_nodes = pd.read_csv(file_path, sep='|', low_memory=False)

        # Ensure required columns exist
        if 'Node_Name' not in df_nodes.columns or 'Description' not in df_nodes.columns:
            raise ValueError(f"CSV file {file_path} must contain 'Node_Name' and 'Description' columns. Found: {df_nodes.columns.tolist()}")

        # Clean data: drop rows where Node_Name or Description is NaN, strip whitespace
        df_cleaned = df_nodes.dropna(subset=['Node_Name', 'Description']).copy()
        df_cleaned.loc[:, 'Node_Name'] = df_cleaned['Node_Name'].astype(str).str.strip()
        df_cleaned.loc[:, 'Description'] = df_cleaned['Description'].astype(str).str.strip()

        # Create map: if duplicate Node_Name exists, keep the first description
        node_map_df = df_cleaned.drop_duplicates(subset=['Node_Name'], keep='first')
        node_name_map = pd.Series(node_map_df['Description'].values, index=node_map_df['Node_Name']).to_dict()
        
        return node_name_map
    except Exception as e:
        print(f"Error loading or processing GSN node file '{file_path}': {e}")
        return {} # Return an empty map on error

# --- Helper function to load Process Importance data ---
def load_process_importance(file_path, separator=None): # Pass separator if not comma, e.g., '\s+' for spaces
    try:
        if separator:
            df_importance = pd.read_csv(file_path, sep=separator, low_memory=False)
        else: # Assumes comma-separated or pandas can infer
            df_importance = pd.read_csv(file_path, low_memory=False)

        if 'Process_Name' not in df_importance.columns or 'Degree' not in df_importance.columns:
            raise ValueError(f"Process importance file ('{file_path}') must contain 'Process_Name' and 'Degree' columns. Found: {df_importance.columns.tolist()}")

        df_cleaned = df_importance.dropna(subset=['Process_Name', 'Degree']).copy()
        df_cleaned.loc[:, 'Process_Name'] = df_cleaned['Process_Name'].astype(str).str.strip()
        # Assuming 'Degree' is the importance value, ensure it's suitable for JSON (e.g., numeric or string)
        # df_cleaned.loc[:, 'Degree'] = pd.to_numeric(df_cleaned['Degree'], errors='coerce') # Optional: convert to numeric

        map_df = df_cleaned.drop_duplicates(subset=['Process_Name'], keep='first')
        process_importance_map = pd.Series(map_df['Degree'].values, index=map_df['Process_Name']).to_dict()
        print(f"Successfully loaded process importance. Map size: {len(process_importance_map)}")
        return process_importance_map
    except Exception as e:
        print(f"Error loading process importance from '{file_path}': {e}")
        return {}

# # --- MODIFIED generate_interpretation_info_from_group FUNCTION ---
# def generate_interpretation_info_from_group(smap_group_data, node_desc_map, process_importance_map):
#     # smap_group_data contains all S_map rows for a specific (Attack_Type, Probabilistic_Value)

#     temp_df_for_grouping = smap_group_data.copy()
#     # Ensure 'Immediate Goal' is string for grouping and lookup, handle NaNs
#     temp_df_for_grouping['__grouping_key_goal_id__'] = temp_df_for_grouping['Immediate Goal'].fillna('__MISSING_ID__').astype(str).str.strip()
    
#     grouped_by_immediate_goal = temp_df_for_grouping.groupby('__grouping_key_goal_id__')

#     final_interpretation_list = [] 

#     for goal_id_for_group, rows_for_this_goal in grouped_by_immediate_goal:
#         if goal_id_for_group == '__MISSING_ID__':
#             print(f"Warning: Skipping S_map rows with missing 'Immediate Goal' ID within an attack group.")
#             continue

#         goal_name_for_group = node_desc_map.get(goal_id_for_group, f"Name not found for ID '{goal_id_for_group}'")
        
#         attribute_contexts_list = []
#         # Variables to store path elements from the *first row* of this goal's group
#         representative_path = "Path Not Available"
#         representative_strategies_payload = []
#         representative_intermediate_goals_payload = []
        
#         first_row_processed_for_path_elements = False

#         for _, s_map_row in rows_for_this_goal.iterrows(): # Iterate over original S_map rows for this specific goal_id
#             # 1. Collect attribute context for every row
#             attribute_contexts_list.append({
#                 "attribute": s_map_row.get("Feature Name", "N/A"),
#                 "state": s_map_row.get("Expected_range", "N/A"),
#                 "attribute_value": s_map_row.get("Feature_Value", "N/A")
#             })

#             # 2. If this is the first row for this goal_id_for_group, extract its path, strategies, and intermediate goals
#             if not first_row_processed_for_path_elements:
#                 representative_path = s_map_row.get("Ordered Intermediate Goal Series", "Path Not Available")

#                 # Process Intermediate Strategies for this first representative row
#                 strategies_str = s_map_row.get("Intermediate Strategies", "")
#                 if pd.notna(strategies_str) and strategies_str.strip():
#                     strategy_ids = [s.strip() for s in strategies_str.split(',') if s.strip()]
#                     for strat_id in strategy_ids:
#                         strategy_description = node_desc_map.get(strat_id, f"Name not found for ID '{strat_id}'")
#                         extracted_process_name = "N/A"
#                         if strategy_description and not strategy_description.startswith("Name not found"):
#                             try:
#                                 words = strategy_description.split()
#                                 if len(words) > 2: extracted_process_name = words[2]
#                                 else: extracted_process_name = "FormatError (short desc)"
#                             except Exception: extracted_process_name = "ErrorExtractingProcess"
#                         process_importance_val = process_importance_map.get(extracted_process_name, "Importance Not Found")
#                         if extracted_process_name.startswith("Name not found")or process_importance_val=="Importance Not Found" :
#                             continue
#                         representative_strategies_payload.append({
# #                             "Strategy_ID": strat_id,
# #                             "Strategy_Name": strategy_description,
#                             "process_name": extracted_process_name,
#                             "process_importance": process_importance_val
#                         })
                
#                 # Process Intermediate Goals for this first representative row
#                 intermediate_goals_str = s_map_row.get("Intermediate Goals", "")
#                 if pd.notna(intermediate_goals_str) and intermediate_goals_str.strip():
#                     intermediate_goal_ids = [g.strip() for g in intermediate_goals_str.split(',') if g.strip()]
#                     for inter_goal_id in intermediate_goal_ids:
#                         representative_intermediate_goals_payload.append({
#                             "goal_id": inter_goal_id,
#                             "goal_name": node_desc_map.get(inter_goal_id, f"Name not found for ID '{inter_goal_id}'")
#                         })
#                 first_row_processed_for_path_elements = True # Mark as processed

#         # Construct the goal-centric object
#         goal_centric_object = {
#             "goal_id": goal_id_for_group,
#             "goal_name": goal_name_for_group,
#             "attribute_contexts": attribute_contexts_list,
#             "affected goal": representative_path,
#             "goal description": representative_intermediate_goals_payload, # User's key "goal" for intermediate goals
#             "process": representative_strategies_payload # User's key "strategy"
            
#         }
#         final_interpretation_list.append(goal_centric_object)
        
#     return final_interpretation_list

# # --- Main script execution ---

# # 1. Load GSN node descriptions (Node ID -> Description map)
# gsn_nodes_file = '.\\GSNIOTDDOS2_node.csv' # Ensure this file path is correct
# node_descriptions = load_and_prepare_gsn_nodes(gsn_nodes_file)

# # 2. Load Process Importance (Process Name -> Degree map)
# process_importance_file = '.\\weighted_pagerank.txt' # Ensure this file path is correct
# # You might need to specify a separator for weighted_pagerank.txt, e.g., sep='\s+' if space-separated
# # If it's comma-separated, pandas might infer it or you can use sep=','
# process_importances = load_process_importance(process_importance_file) # Add separator if needed, e.g. separator='\s+'

# # 3. Assume S_map DataFrame is already loaded and processed.
# # It needs: 'Instance_id', 'Attack_type', 'Probabilistic Value',
# # 'Immediate Goal' (main goal ID for the row),
# # 'Intermediate Strategies' (comma-separated IDs string),
# # 'Intermediate Goals' (comma-separated IDs string),
# # 'Proc_Name', 'Degree' (for main goal's process if still needed),
# # 'Feature Name', 'Expected_range', 'Feature_Value', 'Matching Paths'.



# # 4. Proceed with JSON generation if maps are loaded
# if not S_map.empty and node_descriptions and process_importances:
#     grouped = S_map.groupby(['Attack_type', 'Probabilistic Value'])
#     structured_data = []
    
#     s_map_instance_id = S_map['Instance_id'].iloc[0] if 'Instance_id' in S_map.columns and not S_map.empty else "Default_ID"

#     for (attack, probability), group_data in grouped:
#         traffic_info = {
#             "Type": 'attack',
#             "Spec_version": "dummy",
#             "Id": str(s_map_instance_id),
#             "Created": "N/A",
#             "modified": "N/A",
#             "Name": attack,
#             "probability": float(probability)
#         }
        
#         interpretation_info_list = generate_interpretation_info_from_group(
#             group_data, node_descriptions, process_importances
#         )
        
#         structured_entry = {
#             "traffic_info": traffic_info,
#             "interpretation_info": interpretation_info_list
#         }
#         structured_data.append(structured_entry)

#     json_data = json.dumps(structured_data, indent=4)
#     print(json_data)
#     with open("structured_data_enriched.json", "w") as file:
#         file.write(json_data)
# else:
#     print("Skipping JSON generation due to errors in loading S_map or lookup files.")

In [18]:
import pandas as pd
# Assuming node_desc_map and process_importance_map are pre-loaded as in your script

def generate_interpretation_info_from_group(smap_group_data, node_desc_map, process_importance_map):
    temp_df_for_grouping = smap_group_data.copy()
    # Ensure 'Immediate Goal' is string for grouping and lookup, handle NaNs
    temp_df_for_grouping['__grouping_key_goal_id__'] = temp_df_for_grouping['Immediate Goal'].fillna('__MISSING_ID__').astype(str).str.strip()
    
    grouped_by_immediate_goal = temp_df_for_grouping.groupby('__grouping_key_goal_id__')
    final_interpretation_list = []

    for goal_id_for_group, rows_for_this_goal in grouped_by_immediate_goal:
        if goal_id_for_group == '__MISSING_ID__':
            # print(f"Warning: Skipping S_map rows with missing 'Immediate Goal' ID.") # Optional: for debugging
            continue

        goal_name_for_group = node_desc_map.get(goal_id_for_group, f"Name not found for ID '{goal_id_for_group}'")
        
        # --- Collections for aggregated and unique data ---
        unique_attribute_tuples = set()
        collected_ordered_series_set = set()
        collected_strategy_ids_set = set()
        collected_intermediate_goal_ids_set = set()

        # Iterate over all S_map rows for this specific goal_id
        for _, s_map_row in rows_for_this_goal.iterrows():
            # 1. Collect data for unique attribute contexts
            attr_tuple = (
                s_map_row.get("Feature Name", "N/A"),
                s_map_row.get("Expected_range", "N/A"),
                s_map_row.get("Feature_Value", "N/A")
            )
            unique_attribute_tuples.add(attr_tuple)

            # 2. Collect data for aggregated "affected goal" series
            ogs_str = s_map_row.get("Ordered Intermediate Goal Series", "")
            if pd.notna(ogs_str) and ogs_str.strip():
                collected_ordered_series_set.add(ogs_str.strip())

            # 3. Collect data for aggregated strategies
            strategies_str = s_map_row.get("Intermediate Strategies", "")
            if pd.notna(strategies_str) and strategies_str.strip():
                strategy_ids = [s.strip() for s in strategies_str.split(',') if s.strip()]
                collected_strategy_ids_set.update(strategy_ids)
            
            # 4. Collect data for aggregated intermediate goals
            intermediate_goals_str = s_map_row.get("Intermediate Goals", "")
            if pd.notna(intermediate_goals_str) and intermediate_goals_str.strip():
                intermediate_goal_ids = [g.strip() for g in intermediate_goals_str.split(',') if g.strip()]
                collected_intermediate_goal_ids_set.update(intermediate_goal_ids)

        # --- Process collected data for the output object ---

        # A. Finalize "affected goal" string (from Ordered Intermediate Goal Series)
        # Sort for consistent output order if multiple unique series are joined
        affected_goal_output_str = "; ".join(sorted(list(collected_ordered_series_set))) if collected_ordered_series_set else "Path Not Available"

        # B. Finalize "process" payload (from Intermediate Strategies)
        strategies_payload_list = []
        for strat_id in sorted(list(collected_strategy_ids_set)): # Sort for consistent output
            strategy_description = node_desc_map.get(strat_id, f"Name not found for ID '{strat_id}'")
            extracted_process_name = "N/A"

            # Only attempt to extract process name if strategy_description is not a "not found" message
            if not strategy_description.startswith("Name not found for ID"):
                try:
                    words = strategy_description.split()
                    if len(words) > 2:
                        extracted_process_name = words[2]
                    else:
                        extracted_process_name = "FormatError (short desc)"
                except Exception:
                    extracted_process_name = "ErrorExtractingProcess"
            
            process_importance_val = process_importance_map.get(extracted_process_name, "Importance Not Found")
            
            # Skip if the original strategy ID wasn't found, or process extraction failed, or importance is missing
            if strategy_description.startswith("Name not found for ID") or \
               extracted_process_name in ["N/A", "FormatError (short desc)", "ErrorExtractingProcess"] or \
               process_importance_val == "Importance Not Found":
                # This filter mirrors the original intent: if extracted_process_name.startswith("Name not found") or process_importance_val=="Importance Not Found"
                # The original check `extracted_process_name.startswith("Name not found")` would only trigger if `words[2]` yielded "Name"
                # and `strategy_description` was very specific like "Name not found process...".
                # The check `strategy_description.startswith("Name not found for ID")` is more direct for missing strategy descriptions.
                # The original line: `if extracted_process_name.startswith("Name not found")or process_importance_val=="Importance Not Found" : continue`
                # This implies that even if extracted_process_name was derived, if it itself signaled "Name not found" (unlikely) or if importance was missing, skip.
                # The refined logic above should be more robust:
                #   1. Skip if `strat_id` has no description.
                #   2. Skip if `extracted_process_name` is an error/placeholder.
                #   3. Skip if `process_importance_val` is "Importance Not Found".
                # The user's filter `if extracted_process_name.startswith("Name not found") or process_importance_val=="Importance Not Found" :`
                # Let's use a filter closer to original line 65 intent, but more robust for `extracted_process_name`:
                should_skip = False
                if process_importance_val == "Importance Not Found":
                    should_skip = True
                # Check if extracted_process_name indicates it couldn't be properly determined
                if extracted_process_name in ["N/A", "FormatError (short desc)", "ErrorExtractingProcess"]:
                     should_skip = True
                # The original `extracted_process_name.startswith("Name not found")` is tricky.
                # If strategy_description was "Name not found for ID X", then `extracted_process_name` would be "N/A" with the above logic.
                # The only way `extracted_process_name` itself could be "Name not found.." is if `words[2]` produced it from a valid description, which is not the intent.
                # So, the primary conditions are: valid strategy_description -> valid extracted_process_name -> valid process_importance_val.

                if strategy_description.startswith("Name not found for ID") or process_importance_val == "Importance Not Found":
                     # This is a simpler and more direct interpretation of the likely original skip conditions
                    continue
            
            strategies_payload_list.append({
                "process_name": extracted_process_name,
                "process_importance": process_importance_val
            })
        
        # C. Finalize "goal description" payload (from Intermediate Goals)
        intermediate_goals_payload_list = []
        for inter_goal_id in sorted(list(collected_intermediate_goal_ids_set)): # Sort for consistent output
            goal_name = node_desc_map.get(inter_goal_id, f"Name not found for ID '{inter_goal_id}'")
            # Optionally, filter out goals where name is "Name not found..." if desired
            # if not goal_name.startswith("Name not found for ID"):
            intermediate_goals_payload_list.append({
                "goal_id": inter_goal_id,
                "goal_name": goal_name
            })

        # D. Finalize unique "attribute_contexts" list
        attribute_contexts_list_final = []
        # Sort tuples for consistent output order before converting to dicts
        # Sorting by attribute, then state, then value (all cast to str for robust comparison)
        sorted_attribute_tuples = sorted(
            list(unique_attribute_tuples), 
            key=lambda t: (str(t[0]), str(t[1]), str(t[2]))
        )
        for t_attr, t_state, t_val in sorted_attribute_tuples:
            attribute_contexts_list_final.append({
                "attribute": t_attr,
                "state": t_state,
                "attribute_value": t_val
            })
            
        # Construct the goal-centric object
        goal_centric_object = {
            "goal_id": goal_id_for_group,
            "goal_name": goal_name_for_group,
            "attribute_contexts": attribute_contexts_list_final,
            "affected goal": affected_goal_output_str,
            "goal description": intermediate_goals_payload_list, # Corresponds to user's "goal" key
            "process": strategies_payload_list                 # Corresponds to user's "strategy" key
        }
        final_interpretation_list.append(goal_centric_object)
        
    return final_interpretation_list
# --- Main script execution ---

# 1. Load GSN node descriptions (Node ID -> Description map)
gsn_nodes_file = '.\\GSNIOTDDOS2_node.csv' # Ensure this file path is correct
node_descriptions = load_and_prepare_gsn_nodes(gsn_nodes_file)

# 2. Load Process Importance (Process Name -> Degree map)
process_importance_file = '.\\weighted_pagerank.txt' # Ensure this file path is correct
# You might need to specify a separator for weighted_pagerank.txt, e.g., sep='\s+' if space-separated
# If it's comma-separated, pandas might infer it or you can use sep=','
process_importances = load_process_importance(process_importance_file) # Add separator if needed, e.g. separator='\s+'

# 3. Assume S_map DataFrame is already loaded and processed.
# It needs: 'Instance_id', 'Attack_type', 'Probabilistic Value',
# 'Immediate Goal' (main goal ID for the row),
# 'Intermediate Strategies' (comma-separated IDs string),
# 'Intermediate Goals' (comma-separated IDs string),
# 'Proc_Name', 'Degree' (for main goal's process if still needed),
# 'Feature Name', 'Expected_range', 'Feature_Value', 'Matching Paths'.



# 4. Proceed with JSON generation if maps are loaded
if not S_map.empty and node_descriptions and process_importances:
    grouped = S_map.groupby(['Attack_type', 'Probabilistic Value'])
    structured_data = []
    
    s_map_instance_id = S_map['Instance_id'].iloc[0] if 'Instance_id' in S_map.columns and not S_map.empty else "Default_ID"

    for (attack, probability), group_data in grouped:
        traffic_info = {
            "Type": 'attack',
            "Spec_version": "dummy",
            "Id": str(s_map_instance_id),
            "Created": "N/A",
            "modified": "N/A",
            "Name": attack,
            "probability": float(probability)
        }
        
        interpretation_info_list = generate_interpretation_info_from_group(
            group_data, node_descriptions, process_importances
        )
        
        structured_entry = {
            "traffic_info": traffic_info,
            "interpretation_info": interpretation_info_list
        }
        structured_data.append(structured_entry)

    json_data = json.dumps(structured_data, indent=4)
    print(json_data)
    with open("structured_data_enriched.json", "w") as file:
        file.write(json_data)
else:
    print("Skipping JSON generation due to errors in loading S_map or lookup files.")

Successfully loaded process importance. Map size: 16
[
    {
        "traffic_info": {
            "Type": "attack",
            "Spec_version": "dummy",
            "Id": "38155",
            "Created": "N/A",
            "modified": "N/A",
            "Name": "DDoS_UDP",
            "probability": 0.9999958
        },
        "interpretation_info": [
            {
                "goal_id": "G-13",
                "goal_name": "Transmit  sensor data reading to edge layer",
                "attribute_contexts": [
                    {
                        "attribute": "udp.stream",
                        "state": "udp.stream > 0.00",
                        "attribute_value": 0.7264197026607092
                    }
                ],
                "affected goal": "SI-4 Main|SI-4 Req|G-10",
                "goal description": [
                    {
                        "goal_id": "G-10",
                        "goal_name": "Monitor UDP network traffic in between physical and edge layer"
                    },
                    {
                        "goal_id": "SI-4 Main",
                        "goal_name": "Monitor the system to detect attacks"
                    },
                    {
                        "goal_id": "SI-4 Req",
                        "goal_name": "Monitor network traffic to detect DDoS"
                    }
                ],
                "process": [
                    {
                        "process_name": "SendSensorDataToEdge",
                        "process_importance": 0.016393
                    }
                ]
            },
            {
                "goal_id": "G-14",
                "goal_name": "Record transmitted sensor data reading",
                "attribute_contexts": [
                    {
                        "attribute": "udp.stream",
                        "state": "udp.stream > 0.00",
                        "attribute_value": 0.7264197026607092
                    }
                ],
                "affected goal": "SI-4 Main|SI-4 Req|G-10",
                "goal description": [
                    {
                        "goal_id": "G-10",
                        "goal_name": "Monitor UDP network traffic in between physical and edge layer"
                    },
                    {
                        "goal_id": "SI-4 Main",
                        "goal_name": "Monitor the system to detect attacks"
                    },
                    {
                        "goal_id": "SI-4 Req",
                        "goal_name": "Monitor network traffic to detect DDoS"
                    }
                ],
                "process": [
                    {
                        "process_name": "CollectSensorData",
                        "process_importance": 0.02459
                    }
                ]
            },
            {
                "goal_id": "G-15",
                "goal_name": "Activate actuators as per trigger",
                "attribute_contexts": [
                    {
                        "attribute": "udp.stream",
                        "state": "udp.stream > 0.00",
                        "attribute_value": 0.7264197026607092
                    }
                ],
                "affected goal": "SI-4 Main|SI-4 Req|G-10",
                "goal description": [
                    {
                        "goal_id": "G-10",
                        "goal_name": "Monitor UDP network traffic in between physical and edge layer"
                    },
                    {
                        "goal_id": "SI-4 Main",
                        "goal_name": "Monitor the system to detect attacks"
                    },
                    {
                        "goal_id": "SI-4 Req",
                        "goal_name": "Monitor network traffic to detect DDoS"
                    }
                ],
                "process": [
                    {
                        "process_name": "TriggerActuatorToActivate",
                        "process_importance": 0.094265
                    }
                ]
            },
            {
                "goal_id": "G-16",
                "goal_name": "Transmit trigger flag to actuator",
                "attribute_contexts": [
                    {
                        "attribute": "tcp.ack",
                        "state": "tcp.ack <= 0.00",
                        "attribute_value": 0.0
                    },
                    {
                        "attribute": "tcp.ack_raw",
                        "state": "tcp.ack_raw <= 0.15",
                        "attribute_value": 0.0
                    },
                    {
                        "attribute": "tcp.connection.fin",
                        "state": "tcp.connection.fin <= 0.00",
                        "attribute_value": 0.0
                    },
                    {
                        "attribute": "udp.stream",
                        "state": "udp.stream > 0.00",
                        "attribute_value": 0.7264197026607092
                    }
                ],
                "affected goal": "SI-4 Main|SI-4 Req|G-10; SI-4 Main|SI-4 Req|G-12",
                "goal description": [
                    {
                        "goal_id": "G-10",
                        "goal_name": "Monitor UDP network traffic in between physical and edge layer"
                    },
                    {
                        "goal_id": "G-12",
                        "goal_name": "Monitor TCP network traffic in between edge and cloud layer"
                    },
                    {
                        "goal_id": "SI-4 Main",
                        "goal_name": "Monitor the system to detect attacks"
                    },
                    {
                        "goal_id": "SI-4 Req",
                        "goal_name": "Monitor network traffic to detect DDoS"
                    }
                ],
                "process": [
                    {
                        "process_name": "SendTriggerToActuator",
                        "process_importance": 0.086069
                    }
                ]
            },
            {
                "goal_id": "G-21",
                "goal_name": "Record aggregared sensor data at Cloud layer",
                "attribute_contexts": [
                    {
                        "attribute": "tcp.ack",
                        "state": "tcp.ack <= 0.00",
                        "attribute_value": 0.0
                    },
                    {
                        "attribute": "tcp.ack_raw",
                        "state": "tcp.ack_raw <= 0.15",
                        "attribute_value": 0.0
                    },
                    {
                        "attribute": "tcp.connection.fin",
                        "state": "tcp.connection.fin <= 0.00",
                        "attribute_value": 0.0
                    }
                ],
                "affected goal": "SI-4 Main|SI-4 Req|G-12",
                "goal description": [
                    {
                        "goal_id": "G-12",
                        "goal_name": "Monitor TCP network traffic in between edge and cloud layer"
                    },
                    {
                        "goal_id": "SI-4 Main",
                        "goal_name": "Monitor the system to detect attacks"
                    },
                    {
                        "goal_id": "SI-4 Req",
                        "goal_name": "Monitor network traffic to detect DDoS"
                    }
                ],
                "process": [
                    {
                        "process_name": "ReceivedSensorData",
                        "process_importance": 0.057374
                    }
                ]
            },
            {
                "goal_id": "G-22",
                "goal_name": "Transmit  aggregated sensor data to Cloud layer",
                "attribute_contexts": [
                    {
                        "attribute": "tcp.ack",
                        "state": "tcp.ack <= 0.00",
                        "attribute_value": 0.0
                    },
                    {
                        "attribute": "tcp.ack_raw",
                        "state": "tcp.ack_raw <= 0.15",
                        "attribute_value": 0.0
                    },
                    {
                        "attribute": "tcp.connection.fin",
                        "state": "tcp.connection.fin <= 0.00",
                        "attribute_value": 0.0
                    }
                ],
                "affected goal": "SI-4 Main|SI-4 Req|G-12",
                "goal description": [
                    {
                        "goal_id": "G-12",
                        "goal_name": "Monitor TCP network traffic in between edge and cloud layer"
                    },
                    {
                        "goal_id": "SI-4 Main",
                        "goal_name": "Monitor the system to detect attacks"
                    },
                    {
                        "goal_id": "SI-4 Req",
                        "goal_name": "Monitor network traffic to detect DDoS"
                    }
                ],
                "process": [
                    {
                        "process_name": "SendSensorDataToEdge",
                        "process_importance": 0.016393
                    }
                ]
            },
            {
                "goal_id": "G-23",
                "goal_name": "Transmit trigger flag to edge layer",
                "attribute_contexts": [
                    {
                        "attribute": "tcp.ack",
                        "state": "tcp.ack <= 0.00",
                        "attribute_value": 0.0
                    },
                    {
                        "attribute": "tcp.ack_raw",
                        "state": "tcp.ack_raw <= 0.15",
                        "attribute_value": 0.0
                    },
                    {
                        "attribute": "tcp.connection.fin",
                        "state": "tcp.connection.fin <= 0.00",
                        "attribute_value": 0.0
                    }
                ],
                "affected goal": "SI-4 Main|SI-4 Req|G-12",
                "goal description": [
                    {
                        "goal_id": "G-12",
                        "goal_name": "Monitor TCP network traffic in between edge and cloud layer"
                    },
                    {
                        "goal_id": "SI-4 Main",
                        "goal_name": "Monitor the system to detect attacks"
                    },
                    {
                        "goal_id": "SI-4 Req",
                        "goal_name": "Monitor network traffic to detect DDoS"
                    }
                ],
                "process": [
                    {
                        "process_name": "DecidetoTriggerActuator",
                        "process_importance": 0.155743
                    }
                ]
            }
        ]
    }
]